development:
  adapter: postgresql
  encoding: unicode
  database: performance_app_development
  pool: 5
  username: postgres
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: performance_app_test
  pool: 5
  username: postgres
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: performance_app_production
  pool: 5
  username: postgres
  timeout: 5000


# Use these settings for SQLite:

# # SQLite version 3.x
# #   gem install sqlite3
# #
# #   Ensure the SQLite 3 gem is defined in your Gemfile
# #   gem 'sqlite3'
# #
# default: &default
#   adapter: sqlite3
#   pool: 5
#   timeout: 5000
# 
# development:
#   <<: *default
#   database: db/development.sqlite3
# 
# test:
#   <<: *default
#   database: db/test.sqlite3
# 
# production:
#   <<: *default
#   database: db/production.sqlite3


# Use these settings for MySQL:

# # MySQL.  Versions 5.0+ are recommended.
# #
# # Install the MYSQL driver
# #   gem install mysql2
# #
# # Ensure the MySQL gem is defined in your Gemfile
# #   gem 'mysql2'
# #
# # And be sure to use new-style password hashing:
# #   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
# #
# default: &default
#   adapter: mysql2
#   encoding: utf8
#   pool: 5
#   username: postgres
#   password:
#   socket: /tmp/mysql.sock
# 
# development:
#   <<: *default
#   database: performance_app_development
# 
# test:
#   <<: *default
#   database: performance_app_test
# 
# production:
#   <<: *default
#   database: iteachu_production
#   username: postgres
#   password: 
